name: ThinkBayes2
channels:
  - default
  - conda-forge
  - fastai
dependencies:
  - python
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - statsmodels
  - scipy
  - pymc3
  - arviz
  - python-graphviz
  - mkl-service
  - lxml
  - xlrd
  - html5lib
  - pytables
  - nbconvert
  - pandoc<2.3
  - fastdoc
  - pip
  - pip:
    - jupyter_nbextensions_configurator
    - empiricaldist
    - pytest
    - nbmake
    - jupyter-book
    - ghp-import
