name: tutorial
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - cloudpickle=0.6.1
  - python=3.6
  - numpy=1.14.3
  - matplotlib=3.0.2
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - python.app
  - pip:
    - mlflow>=1.0
