name: pytorch_example
channels:
  - defaults
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - pip:
    - torch==1.4.0
    - torchvision==0.5.0
    - mlflow>=1.0
    - tensorboardX
